// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZgrWTh4WBYhvril-TnITqgjxPPFO3_vM',
    appId: '1:270147714540:web:b1881b7bd185d565ad14c9',
    messagingSenderId: '270147714540',
    projectId: 'flutter-web-application-1a0a9',
    authDomain: 'flutter-web-application-1a0a9.firebaseapp.com',
    databaseURL: 'https://flutter-web-application-1a0a9-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-web-application-1a0a9.firebasestorage.app',
    measurementId: 'G-Y4E5FZ90C5',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZgrWTh4WBYhvril-TnITqgjxPPFO3_vM',
    appId: '1:270147714540:web:b1881b7bd185d565ad14c9',
    messagingSenderId: '270147714540',
    projectId: 'flutter-web-application-1a0a9',
    authDomain: 'flutter-web-application-1a0a9.firebaseapp.com',
    databaseURL: 'https://flutter-web-application-1a0a9-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-web-application-1a0a9.firebasestorage.app',
    measurementId: 'G-Y4E5FZ90C5',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPJbybKeeDX29__tGTYI2A6yXYgleb0cQ',
    appId: '1:270147714540:ios:24cfc9da2b364612ad14c9',
    messagingSenderId: '270147714540',
    projectId: 'flutter-web-application-1a0a9',
    databaseURL: 'https://flutter-web-application-1a0a9-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-web-application-1a0a9.firebasestorage.app',
    androidClientId: '270147714540-camsfvlcaq6fvf9r48sfmm43cpvofkj2.apps.googleusercontent.com',
    iosClientId: '270147714540-2l6jogmmlo12d1jso37qc4hm8ic4be4q.apps.googleusercontent.com',
    iosBundleId: 'com.example.myFlutterWebside',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwtEWppAk-GkvTakHnfhDKzOpErJnYY5Y',
    appId: '1:270147714540:android:b22842f2c0213992ad14c9',
    messagingSenderId: '270147714540',
    projectId: 'flutter-web-application-1a0a9',
    databaseURL: 'https://flutter-web-application-1a0a9-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-web-application-1a0a9.firebasestorage.app',
  );

}